### ISSUE TITLE
解压awb问题

### ISSUE THREAD

**Issue by Token713** [kohos/CriTools#2]
,acb  .awb放一起，拖拽.acb至mix_acb后可以解压出音频，适合解压后音频较少的acb
如果有个acb中有很多cue_id,会提示ERROR: Cannot read property 'NumTracks' of undefined
我怀疑是超过了command窗口字符长度，这个怎么解决

**Comment by kohos** [comment]
能否提供样本文件，方便检查问题

**Comment by Token713** [comment]
> 能否提供样本文件，方便检查问题

https://wwa.lanzous.com/itNUvfwhaaj

**Comment by kohos** [comment]
> > 能否提供样本文件，方便检查问题
> 
> https://wwa.lanzous.com/itNUvfwhaaj

调整了mix_acb的代码，可以试一下

**Comment by Token713** [comment]
> > > 能否提供样本文件，方便检查问题
> > 
> > 
> > https://wwa.lanzous.com/itNUvfwhaaj
> 
> 调整了mix_acb的代码，可以试一下

中午就看到了，谢谢大佬。
https://s1.ax1x.com/2020/08/23/d0sLMF.jpg
顺带问下知道VGMToolbox里这个输出带cue_id是干啥用的吗

**Comment by kohos** [comment]
> > > > 能否提供样本文件，方便检查问题
> > > 
> > > 
> > > https://wwa.lanzous.com/itNUvfwhaaj
> > 
> > 
> > 调整了mix_acb的代码，可以试一下
> 
> 中午就看到了，谢谢大佬。
> https://s1.ax1x.com/2020/08/23/d0sLMF.jpg
> 顺带问下知道VGMToolbox里这个输出带cue_id是干啥用的吗

我没用过这个功能，可能是曲目名称或者曲目id，游戏程序播放曲目时可能需要这个id，解包之后就没什么用途了
